---
- name: Configure web server
  hosts: web_server
  remote_user: yijiay
  gather_facts: no

  tasks:
    - name: Install required packages
      apt:
        name:
          - nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx is running and enabled
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Configure web server
      hosts: webservers
      become: yes
      tasks:
        - name: Install required packages
          apt:
            name:
              - package1
              - package2
            state: present
            update_cache: yes
        ---
