- name: Copy JAR file to container and execute
  hosts: target
  vars:
    jar_file_path: /var/jenkins_home/workspace/petclinic_pipeline/target/petclinic.jar
  tasks:
    - name: Copy JAR file to target container
      copy:
        src: "{{ jar_file_path }}"
        dest: "/"

    - name: Execute the jar file
      shell: java -jar -Dserver.port=8090 -Dserver.address=172.24.0.2 /petclinic.jar
