---
- name: Configure web server
  hosts: web_server
  remote_user: yijiay
  gather_facts: no
  
  tasks:
      - name: Install OpenJDK 17 repository
      become: yes
      apt_repository:
        repo: 'deb http://ppa.launchpad.net/openjdk-r/ppa/ubuntu focal main'
        state: present
        update_cache: yes

      - name: Install OpenJDK 17
        become: yes
        apt:
          name: openjdk-17-jdk
          state: present
          
      - name: Create a directory for the PetClinic app
        become: yes
        file:
          path: /opt/petclinic
          state: directory

      - name: Fetch PetClinic JAR file from Jenkins
        delegate_to: localhost
        fetch:
          src: /var/jenkins_home/workspace/petclinic_pipeline/target/petclinic.jar
          dest: /tmp/petclinic.jar
          flat: yes

      - name: Copy PetClinic JAR file to target machine
        become: yes
        copy:
          src: /tmp/petclinic.jar
          dest: /opt/petclinic/spring-petclinic.jar
          mode: 0644

      - name: Run PetClinic application
        become: yes
        command: nohup java -jar /opt/petclinic/spring-petclinic.jar > /opt/petclinic/petclinic.log 2>&1 &
        args:
          chdir: /opt/petclinic
          creates: /opt/petclinic/petclinic.log
