---
- name: Configure web server
  hosts: web_server
  remote_user: yijiay
  gather_facts: no
  
  tasks:
  
      - name: Download the JDK binaries
      get_url:
        url: https://download.oracle.com/java/20/latest/jdk-20_linux-x64_bin.tar.gz
        dest: /var/jenkins_home/jdk-20_linux-x64_bin.tar.gz
        creates: /var/jenkins_home/jdk-20.0.1

      - name: Unzip the downloaded file
        unarchive:
          src: /var/jenkins_home/jdk-20_linux-x64_bin.tar.gz
          dest: /var/jenkins_home
          remote_src: yes
          creates: /var/jenkins_home/jdk-20.0.1

      - name: Set the JAVA_HOME in /etc/profile file
        lineinfile:
          path: /etc/profile
          state: present
          line: "{{ item }}"
        with_items:
          - 'export JAVA_HOME="/var/jenkins_home/jdk-20.0.1"'
          - 'export PATH=$JAVA_HOME/bin:$PATH'

  
      - name: Create a directory for the PetClinic app
        become: yes
        file:
          path: /opt/petclinic
          state: directory

      - name: Fetch PetClinic JAR file from Jenkins
        delegate_to: localhost
        fetch:
          src: /var/jenkins_home/workspace/petclinic_pipeline/target/petclinic.jar
          dest: /tmp/petclinic.jar
          flat: yes

      - name: Copy PetClinic JAR file to target machine
        become: yes
        copy:
          src: /tmp/petclinic.jar
          dest: /opt/petclinic/spring-petclinic.jar
          mode: 0644

      - name: Run PetClinic application
        become: yes
        command: nohup java -jar /opt/petclinic/spring-petclinic.jar > /opt/petclinic/petclinic.log 2>&1 &
        args:
          chdir: /opt/petclinic
          creates: /opt/petclinic/petclinic.log
